language:ruby
rvm:
 - 2.2
 - jruby
sudo : required
services:
  - docker
before_install:
  - docker build -t jaydeepgami56/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true  jaydeepgami56/docker-react npm run test 
